### ISSUE TITLE
Capybara tests

### ISSUE THREAD

**Issue by chalt0319** [learn-co-curriculum/nyc-sinatra#57]
I'm not sure if this is the proper place to do this, but I think the tests on this, and the playlister lab, are too specific. I write my code, get everything to work, and then I have to spend the same, if not more, time changing my code to "fit" the tests. I spend a lot of time just trying to get the tests to pass, even though my code is working fine. I also feel that the tests restrict creativity. 

I just wanted to let someone know how.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @chalt0319 .

We have taken a look at this lab and will also be revisiting the Sinatra playlister. Unfortunately, due to the specific learning goals of this lab, the tests are designed to check for particular form and variable names, as well as consistent RESTful structures, and it is not possible to abstract them further.

We have added some additional content to the readme and starter code to emphasize focus on test driven development.

We apologize for any frustration you might have encountered during this process but thank you for providing us feedback. 💙
